### ISSUE TITLE
Multiple keys not working

### ISSUE THREAD

**Issue by gpgn** [cardoe/ssh-agent-deploy-key#126]
Hi, I'm happily using your fork to work with GIthub Enterprise URLs, but running into an issue with multiple keys. The first one seems to work but the second one does not (getting a `ERROR: failed to solve: failed to load cache key: failed to fetch remote git@<snip>.git: exit status 128` on doing a docker build that should use the second key). Perhaps I'm hitting this one: https://github.com/webfactory/ssh-agent/issues/178.

Wanted to check if I'm doing something wrong and this should work, or if it is not supported.

```
- uses: ./.github/actions/ssh-agent
      with:
        ssh-private-key: |
              ${{ secrets.FIRST_DEPLOY_KEY }}
              ${{ secrets.SECOND_DEPLOY_KEY }}
```

**Comment by cardoe** [comment]
So you need to mount the `$HOME/.ssh/config` into the docker builder so it can identify the correct key to use. You'll have to use the unique repo URLs so that it can identify the correct key. The way this works is by renaming your repo URLs to something unique so that a key can be associated with each repo.
